export const ACTION_ADD_FAVORITE_COMICS = "ACTION_ADD_FAVORITE_COMICS";
export const ACTION_ADD_FAVORITE_CHARACTERS = "ACTION_ADD_FAVORITE_CHARACTERS";
export const ACTION_ADD_FAVORITE_STORIES = "ACTION_ADD_FAVORITE_STORIES";
export const ACTION_REMOVE_FAVORITE_COMICS = "ACTION_REMOVE_FAVORITE_COMICS";
export const ACTION_REMOVE_FAVORITE_CHARACTERS =
    "ACTION_REMOVE_FAVORITE_CHARACTERS";
export const ACTION_REMOVE_FAVORITE_STORIES = "ACTION_REMOVE_FAVORITE_STORIES";

export const ACTIONS = {
    characters: {
        add: ACTION_ADD_FAVORITE_CHARACTERS,
        remove: ACTION_REMOVE_FAVORITE_CHARACTERS,
    },
    comics: {
        add: ACTION_ADD_FAVORITE_COMICS,
        remove: ACTION_REMOVE_FAVORITE_COMICS,
    },
    stories: {
        add: ACTION_ADD_FAVORITE_STORIES,
        remove: ACTION_REMOVE_FAVORITE_STORIES,
    },
};
